# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(761, 558)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.group_viewer = QtWidgets.QGroupBox(Form)
        self.group_viewer.setGeometry(QtCore.QRect(40, 0, 661, 241))
        self.group_viewer.setObjectName("group_viewer")
        self.gridLayout = QtWidgets.QGridLayout(self.group_viewer)
        self.gridLayout.setObjectName("gridLayout")
        self.graphics_viewer = Viewer(self.group_viewer)
        self.graphics_viewer.setObjectName("graphics_viewer")
        self.gridLayout.addWidget(self.graphics_viewer, 0, 0, 1, 1)
        self.group_choose_image = QtWidgets.QGroupBox(Form)
        self.group_choose_image.setGeometry(QtCore.QRect(40, 250, 661, 71))
        self.group_choose_image.setObjectName("group_choose_image")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_choose_image)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_choose_image = QtWidgets.QPushButton(self.group_choose_image)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/wand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_choose_image.setIcon(icon1)
        self.btn_choose_image.setObjectName("btn_choose_image")
        self.horizontalLayout.addWidget(self.btn_choose_image)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_apply_image = QtWidgets.QPushButton(self.group_choose_image)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_apply_image.setIcon(icon2)
        self.btn_apply_image.setObjectName("btn_apply_image")
        self.horizontalLayout.addWidget(self.btn_apply_image)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.group_decide_position = QtWidgets.QGroupBox(Form)
        self.group_decide_position.setGeometry(QtCore.QRect(30, 320, 686, 91))
        self.group_decide_position.setObjectName("group_decide_position")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.group_decide_position)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_x = QtWidgets.QLabel(self.group_decide_position)
        self.label_x.setObjectName("label_x")
        self.horizontalLayout_2.addWidget(self.label_x)
        self.edit_x = QtWidgets.QLineEdit(self.group_decide_position)
        self.edit_x.setObjectName("edit_x")
        self.horizontalLayout_2.addWidget(self.edit_x)
        self.label_y = QtWidgets.QLabel(self.group_decide_position)
        self.label_y.setObjectName("label_y")
        self.horizontalLayout_2.addWidget(self.label_y)
        self.edit_y = QtWidgets.QLineEdit(self.group_decide_position)
        self.edit_y.setObjectName("edit_y")
        self.horizontalLayout_2.addWidget(self.edit_y)
        self.label_w = QtWidgets.QLabel(self.group_decide_position)
        self.label_w.setObjectName("label_w")
        self.horizontalLayout_2.addWidget(self.label_w)
        self.edit_w = QtWidgets.QLineEdit(self.group_decide_position)
        self.edit_w.setObjectName("edit_w")
        self.horizontalLayout_2.addWidget(self.edit_w)
        self.label_h = QtWidgets.QLabel(self.group_decide_position)
        self.label_h.setObjectName("label_h")
        self.horizontalLayout_2.addWidget(self.label_h)
        self.edit_h = QtWidgets.QLineEdit(self.group_decide_position)
        self.edit_h.setObjectName("edit_h")
        self.horizontalLayout_2.addWidget(self.edit_h)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_apply_position = QtWidgets.QPushButton(self.group_decide_position)
        self.btn_apply_position.setIcon(icon2)
        self.btn_apply_position.setObjectName("btn_apply_position")
        self.horizontalLayout_2.addWidget(self.btn_apply_position)
        self.btn_goback_image = QtWidgets.QPushButton(self.group_decide_position)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/goback.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_goback_image.setIcon(icon3)
        self.btn_goback_image.setObjectName("btn_goback_image")
        self.horizontalLayout_2.addWidget(self.btn_goback_image)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.group_input_text = QtWidgets.QGroupBox(Form)
        self.group_input_text.setGeometry(QtCore.QRect(30, 410, 681, 121))
        self.group_input_text.setObjectName("group_input_text")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.group_input_text)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.edit_txt = QtWidgets.QPlainTextEdit(self.group_input_text)
        self.edit_txt.setObjectName("edit_txt")
        self.verticalLayout.addWidget(self.edit_txt)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_font = QtWidgets.QLabel(self.group_input_text)
        self.label_font.setObjectName("label_font")
        self.horizontalLayout_3.addWidget(self.label_font)
        self.font_chooser = QtWidgets.QFontComboBox(self.group_input_text)
        self.font_chooser.setObjectName("font_chooser")
        self.horizontalLayout_3.addWidget(self.font_chooser)
        self.label_size = QtWidgets.QLabel(self.group_input_text)
        self.label_size.setObjectName("label_size")
        self.horizontalLayout_3.addWidget(self.label_size)
        self.size_chooser = QtWidgets.QComboBox(self.group_input_text)
        self.size_chooser.setObjectName("size_chooser")
        self.size_chooser.addItem("")
        self.size_chooser.addItem("")
        self.size_chooser.addItem("")
        self.horizontalLayout_3.addWidget(self.size_chooser)
        self.btn_check = QtWidgets.QCheckBox(self.group_input_text)
        self.btn_check.setObjectName("btn_check")
        self.horizontalLayout_3.addWidget(self.btn_check)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.btn_apply_text = QtWidgets.QPushButton(self.group_input_text)
        self.btn_apply_text.setIcon(icon2)
        self.btn_apply_text.setObjectName("btn_apply_text")
        self.horizontalLayout_3.addWidget(self.btn_apply_text)
        self.btn_save_image = QtWidgets.QPushButton(self.group_input_text)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save_image.setIcon(icon4)
        self.btn_save_image.setObjectName("btn_save_image")
        self.horizontalLayout_3.addWidget(self.btn_save_image)
        self.btn_goback_position = QtWidgets.QPushButton(self.group_input_text)
        self.btn_goback_position.setIcon(icon3)
        self.btn_goback_position.setObjectName("btn_goback_position")
        self.horizontalLayout_3.addWidget(self.btn_goback_position)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.group_viewer.setTitle(_translate("Form", "Image"))
        self.group_choose_image.setTitle(_translate("Form", "Step 1. Choose Image"))
        self.btn_choose_image.setText(_translate("Form", "Choose Picture"))
        self.btn_apply_image.setText(_translate("Form", "Apply"))
        self.group_decide_position.setTitle(_translate("Form", "Step 2. Decide Position"))
        self.label_x.setText(_translate("Form", "x"))
        self.label_y.setText(_translate("Form", "y"))
        self.label_w.setText(_translate("Form", "w"))
        self.label_h.setText(_translate("Form", "h"))
        self.btn_apply_position.setText(_translate("Form", "Apply"))
        self.btn_goback_image.setText(_translate("Form", "Go Back"))
        self.group_input_text.setTitle(_translate("Form", "Step 3. Input Text"))
        self.label_font.setText(_translate("Form", "Font"))
        self.label_size.setText(_translate("Form", "Size"))
        self.size_chooser.setItemText(0, _translate("Form", "Small"))
        self.size_chooser.setItemText(1, _translate("Form", "Medium"))
        self.size_chooser.setItemText(2, _translate("Form", "Large"))
        self.btn_check.setText(_translate("Form", "With Rect"))
        self.btn_apply_text.setText(_translate("Form", "Apply"))
        self.btn_save_image.setText(_translate("Form", "Save"))
        self.btn_goback_position.setText(_translate("Form", "Go Back"))
from plugin_viewer import Viewer
import icons_rc
